---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --audit-level=moderate --production

  - name: install
    image: node:12
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  - name: test
    image: node:12
    commands:
      - npm test

  # Coverage not implemented yet
  #- name: check-coverage
  #  image: node:12
  #  commands:
  #    - npm run coverage

  - name: build
    image: node:12
    commands:
      - npm run build

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  #- name: docker
  #  image: plugins/docker
  #  settings:
  #    repo: quay.io/natlibfi/melinda-record-update-handler
  #    registry: quay.io
  #    username:
  #      from_secret: docker_username
  #    password:
  #      from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data: aeBnYVyLudHgzZ5AOxT74vgyaK41lQw4eITH5Pn92SvmLhLObilU6b9DujwmXsSL5Pc=
---
kind: secret
name: docker_password
data: 7lw1QYzttW5Ar7R1rm/+35Jr4h6qip9zEmk2bwj0uUqsGoMzo0WAQvMVw5qtyddppaD27YZUVp2WtlxE8jYUYMtOIqkBxkMN4xH+xoQvCLUorBzeGj2Nie2qgY0=
---
kind: secret
name: ssh_key
data: /la6LJaEc+qJAZmcxGHoKepjeRkBkeoHYjgYYzRXH9SD4AptcDIElWf3KhLG/9JHPqPoDjtcYnwCHUkC3PXfyq2W+SmHwIW4Zx185rYyVoYz/kpQlRX1lwpd/PrONjRXwWu5PAv8qqiktmm9kGGqQ3qKYvCVtK5t/XvmNxI5izYRyPYdjnwhN9q+pf2LAyAXdj1rQoqfbsr9Ty5yyaqtbKdnUmvR5tFDb7XWTLSI1SY9rUBnmu9drQ9lQF5luSaWBAvvyQeVWwviAYNlPvFMIyYYhHRqaRRhwY+n7MmOtZVEzDs1uUJOe+Xo+fEUVnN6OeedyEzLmI4o2H2Ghc7QWSdHqVlEfNxMMVg4mz2rJMaUA6m18GKzL19HsisxCK/duZh25dYmNFz9RhVD+9iRkolwkZ0sXYnhqsiJaG6fnTmlcKxuckZegjk80TwNN14bXYjJ/RJ3kTDbkR0LPC8jOHpROvtbSRVUGhnDDv2Bq9zPTrvaVyysBEqJJb9g9V/mo9Q5MsfkYK/fca5HKxeyIO8hrrYy1ywT6u4APBco4BGRvVu0R0IGrL4juJdtztgd/EVRcQxiX+HvTMBiMPzyc2PUaudC3lMdq9byX0hT8nPQ5j4gXEllGRJAS0S7oH4WVGUEcedYiKYuLI7zf2Gu7pdQ9PqvwLoPS46jwcpR2He3oosXannlJoZQ5g5m726Y37VZYggLVG14rsTj7BDSp+sj2VVOpLhuJmBbclVEyyb1zXqXDakkZ3JmImuIYZ62hZTSPimpV0uztrMgdRUwNF5GBgIgsv9iONCwTOHZQziuCU3Tr3/p6vpePsxPvg0Mk3khYABA73Fl/Vq2Knx76LAXsQ7Ilsw604rflXFyODiZ4Dk6Ukbjk7twl6Mg/mLEYY+gXnrzPM74LFftHodL1I+fuH6C6xclNHDQK0bhV6f8EAbKHffNOHw5nfCiPXbFg2mw84Z99aDiDxf9eKFxinz4lKDLWegjnLGNh4PhABq2rWS2V8u6F6HovZzc/LUk5WrjWr3GqT5i8fWzF+GB0MlPBIZoven7UT6Dumd/FN49XIyFnf1nAzMJ35p0PfNeMJh8q45XfWJhshgcnhc+/l0xDx384aQzMLtIhuXC99YHwJOdFrQwg+IzuemZwlfVvsdvG/f+cfBUeXLqcUcoiwW7RhXsMiUjn72bXSB7VMC49aM9d6CjJjMIJMYIg2OhKvP1H8cMhZXf5Vxg4KiMikGNWbMVQct8Y40C+YplJLqGDGiHgLzd5pMgs0sCI4XzOLOnNv1ka+UTYLQLX40dqcjh2J8snpnmYncgPRWzMKvC3HURnrjNF1OuBLqIaBx4UiU0ohnGkSVTZD7labwozYn+ve5UgSew9rgaQHU4PZHTsg2rqztcIWf8Q3MdsEklFtX8sO6Nz2p0ncJ37RhNOjJfz6PFerd+BsQYMyXoYif0p53OnuuI1pkI1JqqFxP418D5+/ix+wJmW5XbpkjM7vhnykM/+Er8lON63QK/tM+/wWr6LUbnrV8XmuV6yRw7HwNwosl2ByaR9S2GPh4ZwVM0H+HqHeFOIkefOSWmSHuKBU7F5Yx+DMgd1/vj++bIq9butxt2SdAVrFKs01lNIwS/TyFrGlT9Sj9Y9YILtyvsMP4Lrb2sCW3wa05pJXnsBHHlqiBLaxJ4OVkYiPwE25+NlUgtLyayXCiNbpHVe5Vwo8XOoVLWPbAzd8K41NJLJnTpHfPLITDgkFVRyY2/gH/Wo5RMcU5CX5yoCM6/f1rM9y014NY2Kmp3HrOZAN9jmSWAYv0cTLKBgu7hMG0nJrvmouydcRSNQRVVtmRWvAbw+0RdeOc1+w6ehC4BZ8Gsvvf74RV2jQF8S9BRFraDZmYEWg5afmUPFEoKMyzRXmtNQSRYIt9Jmvd7mHthY039BaGUdYzNgtRZwLv4XXbLsX5zsSWqTfIf5eHIVcPIsbFbFpk6EysOMjUZZJkk7pfaDBhzoOQLnFjsAHnM0EA/CsJEZVL2itU9SDnnvxo7GEdEdtJf4AkS0K5vY/P5rNQ59hV3LaJ3PrQahrDEnkiEprehqsmLRBs2rAnPcQmpbZmIaig8RKAV0ayO/tOFmghoDiVlyGPnBS5r9VQCo2v02l1GWMckOVp8EHS1+gQ8hMwdAcy0MWp5XwV0tNnsElHcE7bohs+KBI3cCGnrZUcHjizMWtdlkK4Bn2FgL7GE6eeHbfRcWwxnPsQGRg3jGORFzRVgZCfssUZ1TXL0oD4P6nbkPVo1fyGJqQn6tBB6a8cL5il3+zSTgraAwhCbjygJgVEzreH24DUSee4r7ZUWTYf0WhJt/tH18lkUoaoNOKiJrk6uFJQSLDP+/Hc0h6gTOUSoh0SXcTjyxUjp17tU4YqFOhyg/xioH2As0FTIEITkKsI0HH7bLyXrWRQccuQQDdOpickiqsqn+E5xOhR4DEjy+fwfNRhb5zi+M/CpNVUxbchEXkAD2lFgMfxd+YQG6Day/wKLbtRl6WIvh/kBDdTgvvs0S9Ue4Fox+JTzOndcF56xnMsnH8Pif408lXvCfoeI2zH/yaKTV28Q/GrZAuKv/jAyZWawIEhUvXIMKOxKZ0cBMoMxlDAFOXxGurkeoM1WncKDhnjiJ0Fe66G/j4CHIxALG84VLNTyLgg5WTDKpOyi+8RJmCbK85EZtsHWxjpXMmRUAcwRh8SbuGvfrfEXRHZ/HWXNJhQ0MCnisWzHmoGR/3eYNMFJujs7SUZrSoOI7nNDsRt4+X3aC6hRrymR2MbKMMGg6KN7e6r2m6K7T+KxPUVWlD5yi6LNHe2P8DBYWkerf65Dg8sY1030fcfWoMNrWfDhyfffIiYUifqO/qOcX0lIKAN/PM6F5XS4mDLDStiagUkhuOVzKXHWEoyqLtjaGK7/2VhHbuvwdXIVWBCaiktDLtPCM4VqSruIOTw5efvVIwKQYsE+TDJ3fX09eOtOJyja5dK/As6jrZ6gjLEkte3WMlUl9pXuGiZHSPlhKjPYZ0sZG5YR
---
kind: secret
name: gpg_key
data: RgWo6D+1+gAKsZ0ASMconOarLil1HKNZT5vLUjd3A+HOFyNXR7BoPLjXxuOq/LmltSByRvRn33Yy3xUvl1719Al2KsAbF0LAA6x4OAi3WxujhGYgjHQjyakoPSi270XpDD3KwP039E7+ZNs3yZtWxjMbZ2bWxBWqkw8Zen9hgWRDNEhPOYfdD/7/eHdQF3mbvKqjiTMp/K19aUsysq2DF3z89DDsuWB2n71cc3zNWLGzxRbcM34oNxbj5f47iok0K23I1Fk1NVzSoEjPSUvb3VtKIOlwUDDJKxIc50lUZ/sx+JaKijmAcxSJQ1X+rblGm4/cbg03g8sKYpqZca9AXGxY7F+X0D2meA9YKDvtjL9Y+/I1kXurULQLfy/Z8FBwikHmMgCDVKfXMupZ3ayfaCLWYcQ0CzWobr/gG/AlfVWkX6LABCDzo/bOLrqCQSKMA1WOmqHZtGp9Ffkv7tjFY8xsvoXXQjNzHHm0a2wjL90LkE4qT3/hTNuR6gAj3buaxkcJj9+zp1kyPdhKJYXU8pLixt2ixhllBOKSgMjmL/vGl4cW93KYNTeky2X+Xslp3RoQvWDyBdNtzm9pqX+2NKb8AZ3Ec4R4JUfy4J+PY/nCan5/vPuPnR4VCbcmT5h1n44L1W7RP2ylVtW7Q8RBE2boZlnJiYk+sOxwRagWWlFk5JJ+R4dp+XLfblA0PUz0B1I92UY+5ZskPw0kWYYV8eAaZdLkOiFMrzQXFqLjw9UHwggdsJNnJkM4e4+cRq1tmzYsmbyVdtE9ni8m/rmid0J+cOOMqOYAAWvL7/hyhvisXq0FKtq0ZIP1IIsK0nW26IqPW4lmZSSmjh+S5FlT9zCJGJrJjmXMp7R/zguwgRSYQ4ejq858Keg4kqSzTgFKVtSl8VAZstwogY+VDSMdBrZewb372WEdRGJLaEAh6p7kGQxmidWT48oz0te9662vm2yNqCbaNNs6OH4UYynjri0t6Mw0lH4/klRRhf1d/IpuVtp8uRR9gnzO8aKpWkwYGVk/210HSQlIsCcAC5J58xvR+Ba1CD29Akxqy/AwMQr8vd8KjysVl3q5/TL/kUX9/K0sM1H7sZy3ujfYT3RnZeFkqoqbNx/L9nXRM1VdJeMxkgMyMTyIG4jCddveqGBoRp+pVQUUbTmrsGQczHwkETGVIQ/eyrzd+6rUUgBEdEXu5S/5dWDtzBEUywCeJAVkjjSx3iEDoU9Sxp6nKrnRr1w17dCS/utJXp6VuuNXG+R6f/Y5wvzezFIWBge1UgmBEX/fIyLV0sa0V5iBtF9Zfps23oqhIZlcDgUDUaPKwqXgO5BjcQjO9SrFpHMwQaodeqtwldKWIM4dEBNFtUjEZY9f1dHhnFbi5ulMYIjQJYw8mxBWa5RNfRP9VGmE/WG9KNNfn7uq9JoOy7FzyUG0LvB2C2Xi0X0J/c5JS6TXNvlPhOQY0uU/QBoYyR9MS6EN/RGOl3m6zpVTCunIvcmdVmIEvOuo4cpzSqkT61xdUThdIzrMdOgFI8y3nnMlJiMllSqqv68wXeLLMTZZnqkROGPH9Q/ROXamPnnMZMlS2rbcNJ8rlx9gV1c34i3GxzmMvmALZZnKyAHEn73J+svjj+UNFfLXiXD3/8qBbspG5vn+1C/1eNZQaXVhEJGJ17usofYLo0Lihv+X72y1MGqPW4YhAGsrhpU309DXh1U6TXG/jBbmIHVuVtroxqaoMxgE1q5u8upDLQ/etOLcGKDg1B+/rR7M2h7CU1V/5ECKj7dLMGmppoy+m6VgPZps9E6h4hQ+idrzAqF1A1inBoNT4sMUmWfteOpiutfMj8x3Q2lQSbh5JoSlErBDr8/P28tNnLDSTxUbAjtNUQbKgI7p9eKI0QfDAHV+0X7qdmJBs1BmsM94YzI7U70FUt2xcLSZwu9xBHN3OTQgnSvnJT76SrLK1tT76cvYpAtqogBio4QJh6q3kVWFh7uADQokeiii/gmkySQNuxXjA7MGmtDXgJgerzjVp14khWvh/cpdEDSvhfsERrwK+mhzbw2juqTooiG094gAX6vfQjAjf7zZiCozx4gKxssXo+ieXnDRvNIoUVqCHEqTEcixuH3npIoMMnNABHLCQO/hyOP/ffx+5Q6MidcvWn+sJbzWU4J2SwgTZT2yI8KBgOPcvZ17xnfBZYHQIN+9oLvt2oHB5Bxr5n1r7QuRxYhttbEv83VeeQBGAEuZgiP00t8XPTouhEu/vj21mqUffuBVJduS5Dp1XKgfO6v0tzJX/9taet0H/scJFaQyegZ25KanKqar7C3RFktix54bWj8eNlXwiWt/dsRDAIxlVjGC9btSUGVHgPYi8KisyNfprzscZB2aIiHPHPG3f/yCbDqME6j10XQ5kQx2EWLstbC5rMzio8kcysUDbtncnaWQfBSzCPcR88icxSiA3OQrTBIH4I43wA37V55HQG6MwFDgeFv3KAOG9yHhmdzMbyyx0bKmFmBHV0SS3OQoRMwfjS3k5IP99uF7D794JS+L4En/vtKmv69SCdaB+IqictBGyGppTy5Qy0s76Ox34JLq7i5mxLXAnSCRmqyMmKBpN9/wamOzTPbUSWw9zNcMasHndvhwEh266qcGrkUaPgiKn/YEWOA3RQVjv34hpO5wRTWGJAaZA+BzucI0LPvhzwYSmBJN+YWs1BYjXerONjbjNwudBhtOs7u9D/JIAGTHCa13nmqDHWWTGRGrDmNFEGrGhCoto8j6smsqeYsjnZMYR7Ffk9jGVvdYQ85tExocw4QJvjPTkM2auC/34s8ruaLoiTXR52VKRsm/eBUINqMlOf572q9ixEZn5EWheh77meloE9kTmYK9rFGgjvVVzJdsa9mPw07QRDzGOzZUrnNvgpFcrx21g/vCFb/iaAG/4x7RtU0YItLmvQ7QC6Tt4B9IgX9ZrmJKc2ju7yb6NKtcRYNdv+IKqHAROHr4mvVOVnBPvh87k9pTDr8+3SwNQWXRF8QslPrz1gmEOYFbdyrOZ2AG5Ljbn9J1LNWxx8IcL6uWszLju9Gw4SvKLJ55J30Hek7CaiIVIc+arHB7DoIzT/qmfKmbwFPLpUyIp3+dm4GLyHSKNRnYX9ET9Tsr5bhZGl1M8XlstWg5xAeQFNL3+pL4vcvJDYzdTno43VdbNJO0h71zLYK6E6uc8WUqfxCv/nFQshZFw20K+jsA/xj4wcdvVkNV5TRZJxnvR06NuJfGc4ke27UXXcWeEOOc2XlL+nafSss/hOzT1BYRmQeRoVsDMyEpzKQF//BfhTZxDx2W9CFLxIJhm0lO6gl3GgPQnfh1X+0xgeVP+w7NsBFkYEQU6u2J7zBhRJLg4KqG6nDRyPGxfGqUKpGoKIJ8Jv6rdtnxWndFM+nXE5JV9sF5rDJJQ5cf6oiTg1qfcxRusOAF8TT6S8CVdxEhQF+CBkR0ERPbbvEFcElxG6uJG2rCqGaX09SlJDGE38Nibt8VsBT4XK1FhkyKR86DdKpAx+KLXN+bMpe3xRKBspzVJUS9jIC2Nf1264t4t9RMMkHGMthgULCWVLe3A1TA49Cs35krohOEgW82kJfZIGh/W4VpN/z011V6CuU7yrK3oL+z2yNwjU+9q4bt3ljxpd98svhijkOCL1zFVFv4H4IhxMhscvIknsZ5zTZ1SrxMN4agSIEMIanQKu8tLEIG3qGBu9gc6WeQ3kTNsK3Q8B8+kzCvFvYA1EPyua1LCPa6oLeGWy5Ko14MqEYVWeVynOM72nTe2+6FL0LfmAp9IrD3T09n17swXZJQx3QHZgSMoDjPn4yO1avOEerbH6jRfLzLrjolKSen6M5ACran6y07DqaTvBs7I5kovi5ZIr71zw5iBF9ofK2WQNXsWhzRMEvzp0larYg+4+V822LLHKE2YbTZZpN9K7g6UM6F1GLy2M0fDqi/+Tf03dRXDoXYjp3xcOw5Q8rKSQplxZaWGTZHlioyiyoJVUf6h2hsX4PgnAefr/TDIptgVrJ7EdQjG13ThyH/YJTNXHFmv765VfaCcTaIM3lXbMKnNErMxDfU2fjTWjWHOdp8Udmu7YJNdYECPAtg72Fvdcr3MfI4Dfn7L/7qYYdJVMsgLEygoMudJaKASZFv3+HLMm10bc/RLUfOVMFuT366daXqHTqOVmgErpQ3+xS2QjxVqb7qvZYwDP0HM3kRTU205d9QFaH2GYHSqt26aTNNXr2eFFpUz4B9ddR2lDunp5CFzlQdI/LA1uYZIsTgERmEKBuQfjt54WR8wHeCiJm3iwKcFzpw2w28jim5G4Gw93Vv0Jkcze+bkvIlIKNfNut6VoszSLj+Nj9NxJIOqta0JQt1xTFzifrKt3EIys3VkRHZ7ngC40VBtn8XK76+qoJVe1j11WpmYqrQCEJ2g+UXe2DYXHzmPJ5REN/4n60QVQPvQgzT7UjrIJQ6+BcJvcF5t1pdknJJygyz6nW9z1rKITDLqmd5DnA5nu6oyzIH1RcDu7bpojzhI/MsG0umUD9t+fjBDStWvDmy8IedEJv6jp0Dd4kjx58bNhDWrhFicc0JMlvvSbX9JbE4mECzupb+T9ng9CmXa2ji2bigyKpPsjml6pELiYvsxqsbH7UEGCimmP1Jg3ErDUqJf8G9vJ88ch3NMFl4GzGFWumsafsBjTx5J4fbtNPsk6yU1N5fUJ3YOwfG2IpSvDrnXToLt03zRkzR1RW9/HTQ3x7nX2cznXiu9idQCSjQtFdT/jGQdPRRZ4F2GyyipUNLi7Ew4cwltqr8+aL19gqxJXCtHRZ/9CHCrZ3r67YqZx5RqvckMfC21quFo3WgDoG2qRcRKem+CUZC9CSsWwZCHFvDRyvUHis0cM5wEQqe81b2deNi/lpVnei53zQ/idbmTELMSdvNxgS5eXd/sFpOY2MU9HpLa3dRnelgehFW5TOAFhb6grZv+wXtLcaigZ5NU/dr6eK9vTD+x1qqz8A17Ejp29AE8jWHcnd7tAeF9xsX2GR5/VprJtWHTeSE8FfYihOUzljNWVVXYlgJsj244woREBl8Z7XDrvOp8dmEZxtGNEe9Ms9vgaaglPwmYe8Iz2nq6Bac3Z2VvUNeV0tveDp0qjq06jGNB8HHB0VZXNmjQ2oXUsis90gX1KHM1dbwqIiG2b+TMc1HBSKtPKEC++qZM6/NnMVT2c3vPlQL2b3bgxhUDF7suPay2nKLeGPd/Rq7HodjMdMGkMCpBzI8z/npuG2b1s13ud5v7T1Nw4tRAwHBCk+/+rxUO5lTl29qWKT1wP918PnIw4j3P/KWhV0CIrXBQdWZgbhkTSZy/Xj/TQb1L+G84Nxz/rfiq6zrSwSK34bDN5lgnit2h0ujXGKrz9i+Wva/l2bi/4RBCmEMI6or+ZjBW3wA19q1ddUij2KeCt5IPn6NGCq0GFmz5SCZIRkTRwnxxdUYDPgNDTJmMIcM3Sgfd6vc0ZG2dy9eke86l2BSbxmD2u/4pr6nOV+rsis6sOEufvW2WR8upoKbkeS95ba2S4CHc7tJX2SHBo8Il0hwy5ZT5ZfG4BGBZzARjfrYxDKXcI5jA2c9XYVngLbLeZzOwfXcz3ni/E9hsjjhhuSXWKsxbiaTcp7KhwSGe5vctfz/AXQG4znRoi2FwmjwkM95qk4xBL3orOGug3ItahhnwE60jJkxOVLZbYKcjfZpXXDqVwvon5GfK379QrSXTgxCVs0O7IufriYK0OpLPOq1yn1vfDWxJftN3REQaC1QVaxcN+dbEKPVuqBAtnPkqjhgxDUdxVcXk6CpMzIy3ArzTvjKoO+rV7RfekSSQX0BLO3sJ3mwJHpG65en6/GtBQezND+1Q43MZLmBguE1IthRBgnOTmE+9xElhLMxe1uMDO3QWtk61KSiZLI727uP3hSPwzmo6vaHV199ar7pwD6Ugbx/yqW/9S1rTiCGBWogCJvqHzKU7GzODT8f6NzZK3O1C6y9L6sDm9wZPyqFWja/NZOHiuzrAx4EgUujKdNGg692VaaN3723Dd2SuA0Qin3jD0ktl8lqE7WQuEGXLqG3yQ3CHFdr4bPrCmqvE3Ubf8qWjE5yny5uKhydWG16x8Z34pUM03o7ADr2rRoX4WnMhbXaVz9ecDuUzzRAWtrvbB+6DB/3Ri9Wiz3LDB5KxxXo+WUkd2BZycIx6Tei6W7Y0GcdKA+Blp+3cYC8cFILYWuKNoW0L+x20icjOTE0ukTXATqoCtqtbt9ZUyFmuhSQTNQ0HWc1bmmndC2wloYjx1ZIgFtWW6eCzLJxsg2QcfO05NsRONiwKuJxN0ZhfcWshjfy9+GjvTWp6oXYz8/XAIHmkupHpz4DVUEr+UYIl9bQI0NeeCLRB7F7z/wElKeYTiSliQxL2gSFoozVEa4sTD8ViU96NTloi1QKW1tQo2KWSmWV52VL349cW/GEi3iYg5lSVlbWkB7fSm10KCcns6bL+W49v5U5io3NaLpAjQOnv/2DjePN6oMeycZTEsF/Y1Q8A+T4h/HhlmsEmKQ26aEy0Ue5F0McZVRJuBW5YklwXHRVxQ647KyX4lNQfPD/SdqGQMVmJIKcw5PUv2+r+iVhpDNXP40CnJAQYmftRcGZvVFIZ3iOg6i1R68TkbpFxTAD/zAc2VxJCyABVTpzu9HE/n2JOe1gp252eClgpzxO0jJu8+36tF/0xyQfTli+yI8gHqKH3pvVcGr/TA==
---
kind: signature
hmac: 0244200d115dcb2ab2cc69c2accfbfc84f7bbed13448ba9994228e694b7cc705

...
